### PR TITLE
Rewrote in typescript, changed testing suite to vite, ESM & CJS builds

### PR DESCRIPTION
**Pull request by jonluca**
Same as this diff https://github.com/openapi-contrib/json-schema-to-openapi-schema/pull/29 - refactors builds and types, and changes testing suite

### CODE REVIEW

**Review by philsturgeon — APPROVED** [review]

**Comment by jonluca** [comment]
Not sure why the github actions aren't running here? Will push again

**Comment by jonluca** [comment]
Yeah not sure why these aren't running?

**Comment by jonluca** [comment]
@philsturgeon any idea why the build isn't running here? Do i need to be a contributor?

**Comment by philsturgeon** [comment]
Who knows what was going on there but I've merged your changes via another PR! Thank you so much.

**Pull request closed without merging**
