### PR TITLE
fix(nullable-enum): avoid adding duplicate null item

### LINKED ISSUE #34: Duplicate element in enum
If an OpenAPI definition contains an enum property that is 1) nullable and 2) that explicitly contains null in its enum values list, then the converted JSON Schema will have the value null twice in its enum definition, which makes it fail in AJV.

**Example input**
```
{
    "type": "object",
    "properties": {
        "lastError": {
            "type": "string",
            "enum": ["referenceError", "configurationError", "unexpectedError", null],
            "nullable": true
        }
    }
}
```

**Current output**
```
    ...
    "enum": ["referenceError", "configurationError", "unexpectedError", null, null],
    ...
```

### PR DESCRIPTION
**Pull request by mjameswh**
Fix #34

### CODE REVIEW

**Comment by philsturgeon** [comment]
Thank you for this! Can you slap a test on it so we know it’s definitely working?

**Comment by mjameswh** [comment]
Hi guys! Is there anything more we need to do here?

**Review by zoellner — COMMENTED** [review]
I think you want to remove the yarn.lock file from the PR. Otherwise lgtm

**Comment by mjameswh** [comment]
> I think you want to remove the yarn.lock file from the PR. Otherwise lgtm

Done.

**Review by philsturgeon — APPROVED** [review]

**Pull request merged**
