### PR TITLE
Not all unnecessary items are removed from "required" array

### PR DESCRIPTION
**Pull request by ozonep**
Currently there's a bug in a package when removing unnecessary items from "required" array.
When iterating over "required" array it is mutated that makes "for" loop non-reliable, it can skip some properties that should be deleted.

Instead of mutating original array, I create new one and push items that are needed.

Also, replaced deep-equal with fast-deep-equal. Works the same way but should be faster.

### CODE REVIEW

**Comment by philsturgeon** [comment]
Thank you for this. I'm not sure I understand the problem, and there is no change to the tests. Could you update the tests to make sure the feature works, and to make it clear what its doing? Double win :D

**Comment by ozonep** [comment]
> Thank you for this. I'm not sure I understand the problem, and there is no change to the tests. Could you update the tests to make sure the feature works, and to make it clear what its doing? Double win :D

Yeah, I will have a look at the tests, but I'm not sure they need to be updated though :)

Just to clarify what's going on:

"cleanRequired" function literates over "required" array to check if item should be removed or not for every particular case. 
The problem: if item is removed from array, it is removed from the same array "for" loop is iterating over, so data is mutated. That messes up index, so if there are 2+ items in array - some items will be skipped and not deleted.

**Comment by philsturgeon** [comment]
If behviour is changing, tests should change. Otherwise there is no way of knowing if what you want to happen is happening.

**Comment by ozonep** [comment]
Tests added!
Previous tests were wrong, they tested only by removing first element in array, so they always passed.

**Comment by philsturgeon** [comment]
Hey! I spaced before, now I understand. Can you resolve the conflict and I'll get this merged ASAP.

**Comment by XVincentX** [comment]
Closed and rebased in #10 — thanks @ozonep

**Pull request closed without merging**
