### PR TITLE
fix: Add MIT license

### PR DESCRIPTION
**Pull request by autumnfound**

### CODE REVIEW

**Comment by autumnfound** [comment]
Looking into using this for something and was poking around the repo and figured I'd chip in. Cool project guys! Let me know if you need me to change anything for merge.

**Comment by philsturgeon** [comment]
Brilliant, thank you! We’re hoping we won’t need to do much on this now OAS3.1 Schema Objects and JSON Schema are basically the same thing.

**Comment by autumnfound** [comment]
Some tooling doesn't yet support OAS3.1, which is one of the reasons I was looking for something like this! Until everything gets to level and adoption is high, this package definitely still serves a use!

**Comment by philsturgeon** [comment]
Oh absolutely. We're not deleting it, I'm just not planning to pour much time in. I've spent that time making sure everything at stoplight.io supports OAS3.1 instead. :D

**Pull request merged**
